services:
  claude:
    build: .
    container_name: claude-container
    volumes:
      - ~/passpal:/root/workspace
      - ~/flutter:/root/flutter
    stdin_open: true
    tty: true
    working_dir: /root/workspace
    environment:
      - TERM=xterm-256color
    restart: unless-stopped

volumes:
  claude-home:
    driver: local
